Raids:
  Radius: 15
  Time-wait: 120
  Not-enough-players: "&4%raid% requires a party of %min% players!"
  Not-leader: "&4Only the party leader can start this raid!"
  Party-large-or-small: "&4%raid% requires a minimum of %min% players and a maximum of %max% players!"
  Added-queue: "&6You have been added to the queue."
  Kick: "&4You have been kicked from the raid!"
  Kick-end: "&4The raid has ended because your party leader left!"
  Start: "&4&l%raid%/n&6The raid will start in &22 minutes&6. If you are not near the raid NPC you will be kicked from the raid!"
Blocked-cmds-raid:
- /tp
Blocked-cmds:
- /back
Blocked-items-interact:
- 92
Blocked-items-drop:
- 78
- 80
- 86
- 91
Scope-items:
- 293:130