name: CrimeRing
main: com.zeshanaslam.crimering.Main
version: 1.0
author: Zeshan Aslam
description: >
             CrimeRing Plugin.
commands:
  CRReload:
    description: Relaods config.
  Raids:
    description: Raids setup command.
  Action:
    description: Action script command.
  Party:
    description: Party command.