name: CrimeRing
main: com.zeshanaslam.crimering.Main
version: 1.2
author: Zeshan Aslam
description: >
             CrimeRing Plugin.
depend: [ProtocolLib, StackableItems, PhatLoots, Vault, MVdWPlaceholderAPI, SimpleClans, zPermissions, Essentials]
commands:
  CRReload:
    description: Relaods config.
  Raidsetup:
    description: Raids setup command.
  Action:
    description: Action script command.
  Party:
    description: Party command.
  CREdit:
    description: CR edit command.
  CRItem:
    description: CR item command.
  clearchat:
    description: Clears chat.
  Raid:
    description: General Raid command.
  Crhat:
    description: Sets hat.
  crsave:
    description: Save worlds in config.
  npcclear:
    description: Clears all CR NPCs.
  crrpupdate:
    description: Updates resource pack.
  CRFakeBlocks:
    description: Fake blocks command.
  CRRunscript:
    description: Runs script.
  CRLock:
    description: Creates lock.
  Lock:
    description: Manage locks.